export const DEMO_PROFILE = {
  isDemo: true,
  name: 'Demo User',
  age: 34,
  sex: 'male',
  heightCm: 175,
  weightKg: 82,
  targetWeightKg: 75,
  targetDate: (()=>{ const d=new Date(); d.setDate(d.getDate()+70); return d.toISOString().slice(0,10); })(),
  dietType: 'non-vegetarian',
  gymAccess: true,
  workoutDays: 5,
  workoutMinutes: 90,
  goal: 'muscle',
  activityLevel: 'moderate',
  trainingExperience: 'intermediate',
  dailySteps: 7000,
  sleepHours: 7,
  stressLevel: 'moderate',
  cuisinePreference: 'north-indian',
  allergies: '',
  dislikedFoods: '',
  mealsPerDay: 4,
  cookingAvailability: 'moderate',
  budget: 'medium',
  eatingOutFrequency: 'sometimes',
  workoutTiming: 'post'
};
